table DIM_product
	lineageTag: 3b6d5d07-4055-4217-a2f0-7c05a745785c

	column Column1
		dataType: string
		lineageTag: 170fbdc2-6959-4b54-81bb-bc120ebcaafc
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 74304486-5118-4e3a-a640-cd51399abedf
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 68dcb9d4-61dc-48c8-9010-a7eaeeb0e92a
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 95b58e12-4b5f-4830-848d-038ec9992c4e
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 8bfce157-7b2f-4081-84f6-7db684d3ab44
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	partition DIM_product = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(AzureStorage.BlobContents("https://hernanalmacen.blob.core.windows.net/csv-data/dataset_productos_powerquery.pdf"), [Implementation="1.3"]),
				    Table001 = Origen{[Id="Table001"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}})
				in
				    #"Tipo cambiado"

	changedProperty = Name

	annotation PBI_ResultType = Table

